### ISSUE TITLE
.elems is not a multi method

### ISSUE THREAD

**Issue by wayland** [lizmat/Hash-Agnostic#4]
If I try to override .elems, I get:

```
Package 'Table::Driver::Postgres' already has a method 'elems' (did you mean to declare a multi method?)
```
...and if I try to make .elems a multi, I get
```
Cannot have a multi candidate for 'elems' when an only method is also in the package 'Table::Driver::Postgres'
```

This might be a bug inside my head, but it might be something Hash::Agnostic can fix.  

Thanks!

**Comment by lizmat** [comment]
It may be a bug in your head, or a WAT in the language.  But there *is* a way around it.  The problem golfed is this:
```
$ raku -e 'role A { method a { } }; class B does A { multi method a { } }'
===SORRY!=== Error while compiling -e
Cannot have a multi candidate for 'a' when an only method is also in the package 'B'
```
Note that if it wouldn't be a `multi`, there'd be no problem:
```
$ raku -e 'role A { method a { } }; class B does A { method a { } }'
```
So an `only` method does **not** pose an issue.  Yet you want a `multi`, presumably because you want more than one.

You can get around this by declaring a `proto` in the class.  A `proto` is internally also an `only` method.  So:
```
$ raku -e 'role A { method a { } }; class B does A { proto method a(|) {*}; multi method a { } }'
```
works like you probably want.

If you want to access the original method in your new multi, there's a way to do that:
```
$ raku -e 'role A { method a { "A" } }; class B does A { proto method a(|) {*}; multi method a { self.A::a } }; dd B.a'
"A"
```
Note that you can call a method from a role like that directly by making the method name fully qualified.

Hope this helped.  Going to close this issue now.  Please re-open if you disagree  :-)
